import '../models/main_category.dart';
import '../models/sub_category.dart';
import '../models/question.dart';
import '../models/user_profile.dart';
import '../models/game_record.dart';

class MockData {
  static final List<MainCategory> mainCategories = [
    const MainCategory(
      id: 'cat_history',
      name: 'History',
      nameAr: 'التاريخ',
      isActive: true,
      order: 1,
    ),
    const MainCategory(
      id: 'cat_science',
      name: 'Science',
      nameAr: 'العلوم',
      isActive: true,
      order: 2,
    ),
    const MainCategory(
      id: 'cat_geography',
      name: 'Geography',
      nameAr: 'الجغرافيا',
      isActive: true,
      order: 3,
    ),
    const MainCategory(
      id: 'cat_sports',
      name: 'Sports',
      nameAr: 'الرياضة',
      isActive: true,
      order: 4,
    ),
  ];

  static final List<SubCategory> subCategories = [
    const SubCategory(
      id: 'sub_ancient_history',
      mainCategoryId: 'cat_history',
      name: 'Ancient History',
      nameAr: 'التاريخ القديم',
      icon: '🏛️',
      isActive: true,
      order: 1,
    ),
    const SubCategory(
      id: 'sub_modern_history',
      mainCategoryId: 'cat_history',
      name: 'Modern History',
      nameAr: 'التاريخ الحديث',
      icon: '📜',
      isActive: true,
      order: 2,
    ),
    const SubCategory(
      id: 'sub_islamic_history',
      mainCategoryId: 'cat_history',
      name: 'Islamic History',
      nameAr: 'التاريخ الإسلامي',
      icon: '🕌',
      isActive: true,
      order: 3,
    ),
    const SubCategory(
      id: 'sub_physics',
      mainCategoryId: 'cat_science',
      name: 'Physics',
      nameAr: 'الفيزياء',
      icon: '⚛️',
      isActive: true,
      order: 1,
    ),
    const SubCategory(
      id: 'sub_chemistry',
      mainCategoryId: 'cat_science',
      name: 'Chemistry',
      nameAr: 'الكيمياء',
      icon: '🧪',
      isActive: true,
      order: 2,
    ),
    const SubCategory(
      id: 'sub_biology',
      mainCategoryId: 'cat_science',
      name: 'Biology',
      nameAr: 'الأحياء',
      icon: '🧬',
      isActive: true,
      order: 3,
    ),
    const SubCategory(
      id: 'sub_world_capitals',
      mainCategoryId: 'cat_geography',
      name: 'World Capitals',
      nameAr: 'عواصم العالم',
      icon: '🌍',
      isActive: true,
      order: 1,
    ),
    const SubCategory(
      id: 'sub_arab_countries',
      mainCategoryId: 'cat_geography',
      name: 'Arab Countries',
      nameAr: 'الدول العربية',
      icon: '🗺️',
      isActive: true,
      order: 2,
    ),
    const SubCategory(
      id: 'sub_football',
      mainCategoryId: 'cat_sports',
      name: 'Football',
      nameAr: 'كرة القدم',
      icon: '⚽',
      isActive: true,
      order: 1,
    ),
    const SubCategory(
      id: 'sub_olympics',
      mainCategoryId: 'cat_sports',
      name: 'Olympics',
      nameAr: 'الألعاب الأولمبية',
      icon: '🏅',
      isActive: true,
      order: 2,
    ),
  ];

  static final List<Question> questions = [
    const Question(
      id: 'q_ancient_1',
      subCategoryId: 'sub_ancient_history',
      questionText: 'Who built the Great Pyramids of Giza?',
      questionTextAr: 'من بنى أهرامات الجيزة العظيمة؟',
      answer: 'The Ancient Egyptians',
      answerAr: 'المصريون القدماء',
      points: 200,
      isActive: true,
      order: 1,
    ),
    const Question(
      id: 'q_ancient_2',
      subCategoryId: 'sub_ancient_history',
      questionText: 'Which ancient wonder was located in Babylon?',
      questionTextAr: 'أي عجائب الدنيا القديمة كانت في بابل؟',
      answer: 'The Hanging Gardens',
      answerAr: 'الحدائق المعلقة',
      points: 400,
      isActive: true,
      order: 2,
    ),
    const Question(
      id: 'q_ancient_3',
      subCategoryId: 'sub_ancient_history',
      questionText: 'Who was the first Roman Emperor?',
      questionTextAr: 'من كان أول إمبراطور روماني؟',
      answer: 'Augustus Caesar',
      answerAr: 'أغسطس قيصر',
      points: 600,
      isActive: true,
      order: 3,
    ),
    const Question(
      id: 'q_ancient_4',
      subCategoryId: 'sub_ancient_history',
      questionText: 'What ancient city was destroyed by a volcanic eruption?',
      questionTextAr: 'ما المدينة القديمة التي دمرها ثوران بركاني؟',
      answer: 'Pompeii',
      answerAr: 'بومبي',
      points: 800,
      isActive: true,
      order: 4,
    ),
    const Question(
      id: 'q_ancient_5',
      subCategoryId: 'sub_ancient_history',
      questionText: 'Which pharaoh\'s tomb was discovered in 1922?',
      questionTextAr: 'قبر أي فرعون تم اكتشافه عام 1922؟',
      answer: 'Tutankhamun',
      answerAr: 'توت عنخ آمون',
      points: 1000,
      isActive: true,
      order: 5,
    ),
    const Question(
      id: 'q_modern_1',
      subCategoryId: 'sub_modern_history',
      questionText: 'In which year did World War I begin?',
      questionTextAr: 'في أي عام بدأت الحرب العالمية الأولى؟',
      answer: '1914',
      answerAr: '1914',
      points: 200,
      isActive: true,
      order: 1,
    ),
    const Question(
      id: 'q_modern_2',
      subCategoryId: 'sub_modern_history',
      questionText: 'Who was the first person to walk on the moon?',
      questionTextAr: 'من كان أول شخص يمشي على القمر؟',
      answer: 'Neil Armstrong',
      answerAr: 'نيل أرمسترونج',
      points: 400,
      isActive: true,
      order: 2,
    ),
    const Question(
      id: 'q_modern_3',
      subCategoryId: 'sub_modern_history',
      questionText: 'When did the Berlin Wall fall?',
      questionTextAr: 'متى سقط جدار برلين؟',
      answer: '1989',
      answerAr: '1989',
      points: 600,
      isActive: true,
      order: 3,
    ),
    const Question(
      id: 'q_modern_4',
      subCategoryId: 'sub_modern_history',
      questionText: 'Who was the British Prime Minister during WWII?',
      questionTextAr: 'من كان رئيس وزراء بريطانيا خلال الحرب العالمية الثانية؟',
      answer: 'Winston Churchill',
      answerAr: 'ونستون تشرشل',
      points: 800,
      isActive: true,
      order: 4,
    ),
    const Question(
      id: 'q_modern_5',
      subCategoryId: 'sub_modern_history',
      questionText: 'In which year was the United Nations established?',
      questionTextAr: 'في أي عام تأسست الأمم المتحدة؟',
      answer: '1945',
      answerAr: '1945',
      points: 1000,
      isActive: true,
      order: 5,
    ),
    const Question(
      id: 'q_islamic_1',
      subCategoryId: 'sub_islamic_history',
      questionText: 'In which year did the Prophet Muhammad migrate to Medina?',
      questionTextAr: 'في أي عام هاجر النبي محمد إلى المدينة؟',
      answer: '622 CE',
      answerAr: '622 ميلادي',
      points: 200,
      isActive: true,
      order: 1,
    ),
    const Question(
      id: 'q_islamic_2',
      subCategoryId: 'sub_islamic_history',
      questionText: 'Who was the first Caliph after Prophet Muhammad?',
      questionTextAr: 'من كان أول خليفة بعد النبي محمد؟',
      answer: 'Abu Bakr Al-Siddiq',
      answerAr: 'أبو بكر الصديق',
      points: 400,
      isActive: true,
      order: 2,
    ),
    const Question(
      id: 'q_islamic_3',
      subCategoryId: 'sub_islamic_history',
      questionText: 'Which Sultan conquered Constantinople in 1453?',
      questionTextAr: 'أي سلطان فتح القسطنطينية عام 1453؟',
      answer: 'Mehmed II (Fatih)',
      answerAr: 'محمد الفاتح',
      points: 600,
      isActive: true,
      order: 3,
    ),
    const Question(
      id: 'q_islamic_4',
      subCategoryId: 'sub_islamic_history',
      questionText: 'Who led the Muslim forces at the Battle of Yarmouk?',
      questionTextAr: 'من قاد الجيوش الإسلامية في معركة اليرموك؟',
      answer: 'Khalid ibn al-Walid',
      answerAr: 'خالد بن الوليد',
      points: 800,
      isActive: true,
      order: 4,
    ),
    const Question(
      id: 'q_islamic_5',
      subCategoryId: 'sub_islamic_history',
      questionText: 'Which dynasty ruled in Andalusia (Islamic Spain)?',
      questionTextAr: 'أي دولة حكمت في الأندلس؟',
      answer: 'The Umayyads',
      answerAr: 'الأمويون',
      points: 1000,
      isActive: true,
      order: 5,
    ),
    const Question(
      id: 'q_physics_1',
      subCategoryId: 'sub_physics',
      questionText: 'What is the speed of light in vacuum?',
      questionTextAr: 'ما سرعة الضوء في الفراغ؟',
      answer: '299,792,458 m/s',
      answerAr: '299,792,458 متر/ثانية',
      points: 200,
      isActive: true,
      order: 1,
    ),
    const Question(
      id: 'q_physics_2',
      subCategoryId: 'sub_physics',
      questionText: 'Who developed the theory of relativity?',
      questionTextAr: 'من طور نظرية النسبية؟',
      answer: 'Albert Einstein',
      answerAr: 'ألبرت أينشتاين',
      points: 400,
      isActive: true,
      order: 2,
    ),
    const Question(
      id: 'q_physics_3',
      subCategoryId: 'sub_physics',
      questionText: 'What is the fundamental force that holds atoms together?',
      questionTextAr: 'ما القوة الأساسية التي تربط الذرات معاً؟',
      answer: 'The Strong Nuclear Force',
      answerAr: 'القوة النووية القوية',
      points: 600,
      isActive: true,
      order: 3,
    ),
    const Question(
      id: 'q_physics_4',
      subCategoryId: 'sub_physics',
      questionText: 'What particle is known as the God Particle?',
      questionTextAr: 'ما الجسيم المعروف باسم جسيم الله؟',
      answer: 'Higgs Boson',
      answerAr: 'بوزون هيغز',
      points: 800,
      isActive: true,
      order: 4,
    ),
    const Question(
      id: 'q_physics_5',
      subCategoryId: 'sub_physics',
      questionText: 'What is the smallest unit of matter in physics?',
      questionTextAr: 'ما أصغر وحدة للمادة في الفيزياء؟',
      answer: 'Quarks',
      answerAr: 'الكواركات',
      points: 1000,
      isActive: true,
      order: 5,
    ),
    const Question(
      id: 'q_chemistry_1',
      subCategoryId: 'sub_chemistry',
      questionText: 'What is the chemical symbol for Gold?',
      questionTextAr: 'ما الرمز الكيميائي للذهب؟',
      answer: 'Au',
      answerAr: 'Au',
      points: 200,
      isActive: true,
      order: 1,
    ),
    const Question(
      id: 'q_chemistry_2',
      subCategoryId: 'sub_chemistry',
      questionText: 'What is the pH of pure water?',
      questionTextAr: 'ما الأس الهيدروجيني للماء النقي؟',
      answer: '7',
      answerAr: '7',
      points: 400,
      isActive: true,
      order: 2,
    ),
    const Question(
      id: 'q_chemistry_3',
      subCategoryId: 'sub_chemistry',
      questionText: 'Who created the periodic table of elements?',
      questionTextAr: 'من أنشأ الجدول الدوري للعناصر؟',
      answer: 'Dmitri Mendeleev',
      answerAr: 'ديمتري مندليف',
      points: 600,
      isActive: true,
      order: 3,
    ),
    const Question(
      id: 'q_chemistry_4',
      subCategoryId: 'sub_chemistry',
      questionText: 'What is the most abundant element in the universe?',
      questionTextAr: 'ما العنصر الأكثر وفرة في الكون؟',
      answer: 'Hydrogen',
      answerAr: 'الهيدروجين',
      points: 800,
      isActive: true,
      order: 4,
    ),
    const Question(
      id: 'q_chemistry_5',
      subCategoryId: 'sub_chemistry',
      questionText: 'What type of bond shares electrons between atoms?',
      questionTextAr: 'ما نوع الرابطة التي تشارك الإلكترونات بين الذرات؟',
      answer: 'Covalent Bond',
      answerAr: 'رابطة تساهمية',
      points: 1000,
      isActive: true,
      order: 5,
    ),
    const Question(
      id: 'q_biology_1',
      subCategoryId: 'sub_biology',
      questionText: 'What is the powerhouse of the cell?',
      questionTextAr: 'ما مصدر الطاقة في الخلية؟',
      answer: 'Mitochondria',
      answerAr: 'الميتوكوندريا',
      points: 200,
      isActive: true,
      order: 1,
    ),
    const Question(
      id: 'q_biology_2',
      subCategoryId: 'sub_biology',
      questionText: 'What molecule carries genetic information?',
      questionTextAr: 'ما الجزيء الذي يحمل المعلومات الوراثية؟',
      answer: 'DNA',
      answerAr: 'الحمض النووي',
      points: 400,
      isActive: true,
      order: 2,
    ),
    const Question(
      id: 'q_biology_3',
      subCategoryId: 'sub_biology',
      questionText: 'What process do plants use to make food?',
      questionTextAr: 'ما العملية التي تستخدمها النباتات لصنع الغذاء؟',
      answer: 'Photosynthesis',
      answerAr: 'التمثيل الضوئي',
      points: 600,
      isActive: true,
      order: 3,
    ),
    const Question(
      id: 'q_biology_4',
      subCategoryId: 'sub_biology',
      questionText: 'How many chromosomes do humans have?',
      questionTextAr: 'كم عدد الكروموسومات في الإنسان؟',
      answer: '46',
      answerAr: '46',
      points: 800,
      isActive: true,
      order: 4,
    ),
    const Question(
      id: 'q_biology_5',
      subCategoryId: 'sub_biology',
      questionText: 'What is the largest organ in the human body?',
      questionTextAr: 'ما أكبر عضو في جسم الإنسان؟',
      answer: 'Skin',
      answerAr: 'الجلد',
      points: 1000,
      isActive: true,
      order: 5,
    ),
    const Question(
      id: 'q_football_1',
      subCategoryId: 'sub_football',
      questionText: 'Which country won the 2022 FIFA World Cup?',
      questionTextAr: 'أي دولة فازت بكأس العالم 2022؟',
      answer: 'Argentina',
      answerAr: 'الأرجنتين',
      points: 200,
      isActive: true,
      order: 1,
    ),
    const Question(
      id: 'q_football_2',
      subCategoryId: 'sub_football',
      questionText: 'Who has won the most Ballon d\'Or awards?',
      questionTextAr: 'من حصل على أكبر عدد من جوائز الكرة الذهبية؟',
      answer: 'Lionel Messi',
      answerAr: 'ليونيل ميسي',
      points: 400,
      isActive: true,
      order: 2,
    ),
    const Question(
      id: 'q_football_3',
      subCategoryId: 'sub_football',
      questionText: 'Which club has won the most UEFA Champions League titles?',
      questionTextAr: 'أي نادي فاز بأكبر عدد من بطولات دوري أبطال أوروبا؟',
      answer: 'Real Madrid',
      answerAr: 'ريال مدريد',
      points: 600,
      isActive: true,
      order: 3,
    ),
    const Question(
      id: 'q_football_4',
      subCategoryId: 'sub_football',
      questionText: 'In which year was the first FIFA World Cup held?',
      questionTextAr: 'في أي عام أقيمت أول بطولة كأس العالم؟',
      answer: '1930',
      answerAr: '1930',
      points: 800,
      isActive: true,
      order: 4,
    ),
    const Question(
      id: 'q_football_5',
      subCategoryId: 'sub_football',
      questionText: 'Who is the all-time top scorer in World Cup history?',
      questionTextAr: 'من هو الهداف التاريخي لكأس العالم؟',
      answer: 'Miroslav Klose',
      answerAr: 'ميروسلاف كلوزه',
      points: 1000,
      isActive: true,
      order: 5,
    ),
    const Question(
      id: 'q_capitals_1',
      subCategoryId: 'sub_world_capitals',
      questionText: 'What is the capital of Japan?',
      questionTextAr: 'ما عاصمة اليابان؟',
      answer: 'Tokyo',
      answerAr: 'طوكيو',
      points: 200,
      isActive: true,
      order: 1,
    ),
    const Question(
      id: 'q_capitals_2',
      subCategoryId: 'sub_world_capitals',
      questionText: 'What is the capital of Australia?',
      questionTextAr: 'ما عاصمة أستراليا؟',
      answer: 'Canberra',
      answerAr: 'كانبيرا',
      points: 400,
      isActive: true,
      order: 2,
    ),
    const Question(
      id: 'q_capitals_3',
      subCategoryId: 'sub_world_capitals',
      questionText: 'What is the capital of Brazil?',
      questionTextAr: 'ما عاصمة البرازيل؟',
      answer: 'Brasília',
      answerAr: 'برازيليا',
      points: 600,
      isActive: true,
      order: 3,
    ),
    const Question(
      id: 'q_capitals_4',
      subCategoryId: 'sub_world_capitals',
      questionText: 'What is the capital of Switzerland?',
      questionTextAr: 'ما عاصمة سويسرا؟',
      answer: 'Bern',
      answerAr: 'برن',
      points: 800,
      isActive: true,
      order: 4,
    ),
    const Question(
      id: 'q_capitals_5',
      subCategoryId: 'sub_world_capitals',
      questionText: 'What is the capital of New Zealand?',
      questionTextAr: 'ما عاصمة نيوزيلندا؟',
      answer: 'Wellington',
      answerAr: 'ويلينغتون',
      points: 1000,
      isActive: true,
      order: 5,
    ),
  ];

  static UserProfile getMockUserProfile(String userId) {
    return UserProfile(
      id: userId,
      email: 'test@example.com',
      name: 'Test User',
      mobile: '+966501234567',
      trialsRemaining: 5,
      availableGames: 0,
      createdAt: DateTime.now().toIso8601String(),
    );
  }

  static List<GameRecord> getMockGameRecords(String userId) {
    return [
      GameRecord(
        id: 'game_1',
        userId: userId,
        gameName: 'Classic Game 1',
        leftTeamName: 'Blue Team',
        rightTeamName: 'Red Team',
        leftTeamScore: 3200,
        rightTeamScore: 2800,
        currentTurn: 'left',
        status: 'completed',
        winner: 'Blue Team',
        playedQuestions: ['q_ancient_1', 'q_ancient_2', 'q_modern_1'],
        selectedSubcategories: ['sub_ancient_history', 'sub_modern_history'],
        playCount: 1,
        createdAt:
            DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
        updatedAt:
            DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
        completedAt:
            DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
      ),
      GameRecord(
        id: 'game_2',
        userId: userId,
        gameName: 'Science Challenge',
        leftTeamName: 'Einstein',
        rightTeamName: 'Newton',
        leftTeamScore: 1800,
        rightTeamScore: 2400,
        currentTurn: 'right',
        status: 'in_progress',
        playedQuestions: ['q_physics_1', 'q_chemistry_1'],
        selectedSubcategories: ['sub_physics', 'sub_chemistry'],
        playCount: 1,
        createdAt:
            DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
        updatedAt:
            DateTime.now().subtract(const Duration(hours: 2)).toIso8601String(),
      ),
    ];
  }

  static List<SubCategory> getSubCategoriesForMainCategory(
      String mainCategoryId) {
    return subCategories
        .where((sub) => sub.mainCategoryId == mainCategoryId)
        .toList();
  }

  static List<Question> getQuestionsForSubCategories(
      List<String> subCategoryIds) {
    return questions
        .where((q) => subCategoryIds.contains(q.subCategoryId))
        .toList();
  }

  static Question? getQuestionById(String questionId) {
    try {
      return questions.firstWhere((q) => q.id == questionId);
    } catch (e) {
      return null;
    }
  }
}
